### ISSUE TITLE
aws.EUWest is hard-coded

### ISSUE THREAD

**Issue by zainhoda** [Luzifer/mondash#1]
Perhaps this should instead be read by an environment variable. Since you allow the name of the S3 bucket as an input, the region also should be an input since you get an error saying:

"Error while storing dashboard: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint."

**Comment by Luzifer** [comment]
By switching to the official aws-sdk-go library region is now loaded from `AWS_REGION`
